# Generated by Django 4.2.16 on 2024-10-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LadoDireito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img_Direito')),
                ('zap', models.CharField(max_length=30)),
                ('instagram', models.TextField(max_length=50)),
                ('youtube', models.TextField(max_length=50)),
                ('linkedin', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
    ]
