# Generated by Django 4.2.16 on 2024-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_ladodireito_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=100)),
            ],
        ),
    ]
