# Generated by Django 4.2.16 on 2024-10-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_videoapresentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladodireito',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ladodireito',
            name='instagram',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ladodireito',
            name='linkedin',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ladodireito',
            name='youtube',
            field=models.CharField(max_length=70),
        ),
    ]
