# Generated by Django 4.2.16 on 2024-10-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_ladodireito_email_alter_ladodireito_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('img_projeto', models.ImageField(upload_to='img_projeto')),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.TextField()),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
