# Generated by Django 4.2.16 on 2024-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
