# Generated by Django 4.2.16 on 2024-10-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_projeto_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='link',
            new_name='github',
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_sistema',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
